-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: 86b1c9da8e917a77c975b14666513d6bd45a3b03
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args: ['-i', '--ignore=E265,E309,E501', '-v']
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: flake8
-   repo: git@github.com:pre-commit/pre-commit
    sha: 061ac8168235070e39d5458c55839517b6f97920
    hooks:
    -   id: validate_config
    -   id: validate_manifest
