
-
    repo: git@github.com:pre-commit/pre-commit-hooks
    sha: 10c042c99c061b90e4ea11d52e3c5fc93f94b373
    hooks:
        -
            id: pyflakes
            files: '\.py$'
        -
            id: debug-statements
            files: '\.py$'

-
    repo: git@github.com:pre-commit/pre-commit
    sha: c77d65d9cbbcf30e2be005f5ba8b63447deedc1e
    hooks:
        -
            id: validate_manifest
            files: /manifest.yaml
        -
            id: validate_config
            files: /\.pre-commit-config.yaml
