-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: e0a6e66528c8335599408cbefe7ebf9e7e15ccb3
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args: ['-i', '--ignore=E265,E309,E501']
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: flake8
-   repo: git@github.com:pre-commit/pre-commit
    sha: 3cac9489b3886f72b00f83d5128c2b22ea2fbcca
    hooks:
    -   id: validate_config
    -   id: validate_manifest
