
-
    repo: git@github.com:pre-commit/pre-commit-hooks
    sha: 3d3427e85ff938668ef3d7884233a147bd760082
    hooks:
        -
            id: pyflakes
            files: '\.py$'
        -
            id: debug-statements
            files: '\.py$'
        -
            id: trailing-whitespace
            files: '\.(py|sh|yaml)'

-
    repo: git@github.com:pre-commit/pre-commit
    sha: c77d65d9cbbcf30e2be005f5ba8b63447deedc1e
    hooks:
        -
            id: validate_manifest
            files: /manifest.yaml
        -
            id: validate_config
            files: /\.pre-commit-config.yaml
