-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: 8aa14d218d0fe5a2c486498269b3e37d3ba5aad2
    hooks:
    -   id: pyflakes
        files: \.py$
    -   id: debug-statements
        files: \.py$
    -   id: trailing-whitespace
        files: \.(py|sh|yaml)$
    -   id: name-tests-test
        files: tests/.*\.py
    -   id: end-of-file-fixer
        files: \.(py|sh|yaml)$
-   repo: git@github.com:pre-commit/pre-commit
    sha: c300a11a973e0e2d88662aef4b282881d0f17b4a
    hooks:
    -   id: validate_manifest
        files: /manifest.yaml
    -   id: validate_config
        files: /\.pre-commit-config.yaml
