dist: xenial
language: python
matrix:
    include:  # These should match the tox env list
    -   env: TOXENV=py27
    -   env: TOXENV=py36
        python: 3.6
    -   env: TOXENV=py37
        python: 3.7
    -   env: TOXENV=pypy
        python: pypy2.7-5.10.0
install: pip install coveralls tox
script: tox
before_install:
  # Install git-lfs for a test
  - './get-git-lfs.py && export PATH="/tmp/git-lfs:$PATH"'
after_success: coveralls
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
        - /tmp/git-lfs
